services:
  usage-persist:
    image: ${CLIPROXYAPI_USAGE_PERSIST_IMAGE:-trieu04/cli-proxy-api-usage-persist:latest}
    build: .
    # env_file:
    #   - path: .env
    #     required: false
    environment:
      CLIPROXYAPI_BASE_URL: ${CLIPROXYAPI_BASE_URL:-}
      CLIPROXYAPI_MANAGEMENT_KEY: ${CLIPROXYAPI_MANAGEMENT_KEY:-}
    volumes:
      - usage-persist-data:/data
    restart: unless-stopped

volumes:
  usage-persist-data:
